### ISSUE TITLE
Container height won't be resized when state reducer is empty (array list)

### ISSUE THREAD

**Issue by mkhuda** [skoob13/react-masonry-infinite#1]
Hi, skoob.
I have a minor problem when use **react-masonry-infinite**, so if i emptying the state reducer that supplied element within `componentWillReceiveProps()` then the height of container won't be resized from previous contained element in container. Except if I refresh the page or go to somewhere from my component then go back to my **react-masonry-infinite** contained component.

**Comment by skoob13** [comment]
I'm not sure, but it can be related to https://github.com/skoob13/react-masonry-infinite/issues/4. Closing since due date.
