### ISSUE TITLE
Add Example note re: workaround for npm issue ?

### ISSUE THREAD

**Issue by pk1u** [skoob13/react-masonry-infinite#11]
I believe I ran into this issue while attempting to run example with current versions of node and npm; this was closed because "...this is not actionable for us--it's just how npm bin works.":
https://github.com/facebookincubator/create-react-app/issues/200

Eg, reinstalling node modules resolves this:

$ rm -rf node_modules
$ npm install

Is this issue commonly known, or should this be noted in the example readme ?

**Comment by skoob13** [comment]
I don't think so. It's a specific case, that should be addressed to `create-react-app`.
