### ISSUE TITLE
loadMore is async function

### ISSUE THREAD

**Issue by wxianfeng** [skoob13/react-masonry-infinite#12]
when my `loadMore` is a async function

it will exec many same request to  server, how to fix this ?

3x

**Comment by ComputerCarl** [comment]
You could try setting state (using setState async syntax) of hasMore in your loadMore function.

**Comment by skoob13** [comment]
This issue should be addressed to [react-infinite-scroller](https://github.com/CassetteRocks/react-infinite-scroller).
