### ISSUE TITLE
Layout breaks when image is `img`

### ISSUE THREAD

**Issue by c0dester** [skoob13/react-masonry-infinite#14]
When I use masonry with `img` as a child, layout breaks. Or maybe I'm making sth wrong? When I use `div` (as in your example), everything works ok. My code is very the same is in your example. When I resize screen, then layout is set correctly. Please check: [this gif](https://media.giphy.com/media/l4EoXTs5MZ3tkH2yQ/giphy.gif)

**Comment by joshuavandijk** [comment]
I'm having the exact same issue

**Comment by skoob13** [comment]
Bricks.js has an issue [here](https://github.com/callmecavs/bricks.js/issues/39). I recommend to wrap images in div tag.

**Comment by bsurai** [comment]
Regard `I recommend to wrap images in div tag`. @joshuavandijk @c0dester did this recomendation help you? I tried to wrap images in div tag but I got the same result?

**Comment by joshuavandijk** [comment]
@bsurai I still haven't found a way to fix this other than setting each img to a predefined fixed height, which is not an ideal solution at all. Wrapping in a div doesn't seem to change anything.

**Comment by skoob13** [comment]
@bsurai @joshuavandijk Bricks.js relies on a element height on a first render, so you get the broken layout. This component is suitable mostly for a static data. If you'd like to use it with dynamic data, you have to "force pack" Bricks.js instance every time what can be not the best solution (but for the most cases should be okay).

For your case try to look other modules e.g. [masonry of react-virtualized](https://bvaughn.github.io/react-virtualized/#/components/Masonry) or you `.forcePack()` instance method.

**Comment by jmbothe** [comment]
Hello all! I am having the same problem, and I was wondering if someone could tell me how exactly to call `.forcePack()`? thanks :)

EDIT : nevermind,I figured it out :)

**Comment by andreieuganox** [comment]
@jmbothe hei, can you pls point out how you used `.forcePack()`? It is a bit confusing on how to use Methods in docs... Thank you in advance!

**Comment by jmbothe** [comment]
@popovprodigyai  so, I didn't actually end up calling `forcePack()` as an instance method. Rather, I realized that setting the prop `pack` to `true` triggers `forcePack()` on every update. I just wasn't reading the docs closely.

https://github.com/skoob13/react-masonry-infinite#props
