### ISSUE TITLE
syntax error on your basic example

### ISSUE THREAD

**Issue by skdkim** [skoob13/react-masonry-infinite#2]
<MasonryInfiniteScroller hasMore={this.state.hasMore} loadMore={() => this.setState({ elements: this.state.elements.push("Element") })}>
    {
        this.state.elements.map((el, index) =>
            <div key={index}/>
        )
    }
</MasonryInfiniteScroller>

you were just missing a closing curly brace right before the greater than in the top tag.

**Comment by skoob13** [comment]
Thanks. Fixed.
