### ISSUE TITLE
Wrong positions when images loaded

### ISSUE THREAD

**Issue by vampics** [skoob13/react-masonry-infinite#4]
The component has wrong positions when images will be loaded after the first positioning.
Nice would be a function for updating the positioning after loading images or a callback method

**Comment by hew** [comment]
I am experiencing this also.

**Comment by sea129** [comment]
I am thinking of adding onLoad handler on img tag to trigger bricks to pack() again or even use onLoad to toggle a flag variable so that brick know when to pack or update inside componentDidUpdate.

Any other solutions?

**Comment by vampics** [comment]
I´ve solved it fast und extrem dirty ( must be done fast :D ) with adding the onload handler and set the instance variable globally. So i can use instance.pack() in the handler function. But it isn´t a correct solution.

**Comment by skoob13** [comment]
This component is mostly suitable for static data. I've created few instance methods like Bricks.js instance **update** and **pack**. Pack method generates again a full tree, so there can be performance issues.

Also there is a prop **packed** that recreates a tree when children change.
